config/routes.rb
Rails.application.routes.draw do

  root 'home#main'
  get 'home/login'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
  
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/login.html.erb
<!-- Login page -->
<div class="jumbotron">
  <h1>Site under development!</h1>
  <p>See you soon</p>
  <%= link_to 'Back', root_path, class:'btn btn-primary btn-lg margin' %>
  </div>

app/views/home/main.html.erb
<!-- Body rendred in the main layout -->
<div>
<div class="panel panel-default">
  <div class="panel-body center">
    
  <%= link_to 'About Us', root_path, class:'btn btn-primary btn-lg margin' %>
  <%= link_to 'Register', root_path, class:'btn btn-primary btn-lg margin' %>
  <%= link_to 'News', root_path, class:'btn btn-primary btn-lg margin' %>
  <%= link_to 'Contact Us', root_path, class:'btn btn-primary btn-lg margin' %>
  <%= link_to 'Help', root_path, class:'btn btn-primary btn-lg margin' %>
 
</div>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= image_tag("http://cdn.sheknows.com/articles/2013/04/Puppy_2.jpg", :alt => "rss feed") %>
        <div class="caption center">
        <h4>Caption</h4>
        </div>
     </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= image_tag("http://cdn.sheknows.com/articles/2013/04/Puppy_2.jpg", :alt => "rss feed") %>
        <div class="caption center">
        <h4>Caption</h4>
        </div>
     </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= image_tag("http://cdn.sheknows.com/articles/2013/04/Puppy_2.jpg", :alt => "rss feed") %>
        <div class="caption center">
        <h4>Caption</h4>
        </div>
     </div>
  </div>
  </div>
</div>

<div>
  <!-- Table -->
  <table class="table table-bordered table-striped center">
        <tr> 
         <td><h4>Name</h4></td>
          <td><h4>Breed</h4></td>
          <td><h4>Weight</h4></td>
        </tr>
        <tr>
          <td>Brian</td>
         <td>Lab</td>
          <td>51</td>
        </tr>
        <tr>
          <td >Kieran</td>
          <td>Samoyed</td>
          <td>32</td>
        </tr>
        <tr>
          <td>Renata</td>
          <td>Coonhound</td>
          <td>29</td>
        </tr>
        <tr>
          <td >Ving</td>
          <td>Boxer</td>
          <td>51</td>
        </tr>
  </table>
</div>
<!--render owl carousel from slider -->
<div>
  <%= render'shared/slider' %>
</div>

</div>

app/views/layouts/application.html.erb
<!-- Layout for the Web page -->
<!DOCTYPE html>
<html>
<head>
  <title>Sai Sindhu Matam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
<!-- Render header -->
<%= render'shared/header' %>
</div>
<div class='container'>
<!-- Renders Body from the main page -->
<%= yield %>
</div>

</body>
</html>

app/views/shared/_header.html.erb
<!-- nav-bar header to be rendered in the main layout -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <!-- Brand image in the nav-bar -->  
      <a class="navbar-brand" href="#">
         <%= image_tag("http://www.hollisdesigns.co.uk/images/separators/separator_blog_200x50px.png", :alt => "Brand") %>
      </a>
    </div>
    <!-- Home and Login page navigation -->
<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
  
    <ul class="nav nav-pills marginnav">
        <li class="navbar-text"><%= link_to 'Home', root_path%> </li>
        
      <li class="navbar-text"><%= link_to 'Login',home_login_path %></li>
      </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_slider.html.erb
<!-- owl carousel for image slider -->

  <div id="owl-demo">
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/1.jpg", :alt => "Image 1") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/2.jpg", :alt => "Image 2") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/3.jpg", :alt => "Image 3") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/4.jpg", :alt => "Image 4") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/5.jpg", :alt => "Image 5") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/6.jpg", :alt => "Image 6") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/7.jpg", :alt => "Image 7") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/8.jpg", :alt => "Image 8") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/9.jpg", :alt => "Image 9") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/10.jpg", :alt => "Image 10") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/11.jpg", :alt => "Image 11") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/12.jpg", :alt => "Image 12") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/13.jpg", :alt => "Image 13") %></div>
  <div class="item"><%= image_tag("http:\/\/numberonelarge.com\/tapjoy\/images\/14.jpg", :alt => "Image 14") %></div>
  </div>

<link rel = "stylesheet" href="owl-carousel/owl.carousel.css"> 
  <link rel = "stylesheet" href="owl-carousel/owl.theme.css"> 
  <script src = "jqery-1.9.1.min.js"></script>
  <script src = "assets/owl/carousel/owl.carousel.js"></script>
  <script> 
  $(document).ready(function() {
 
  $("#owl-demo").owlCarousel({
 
      autoPlay: 3000, //Set AutoPlay to 3 seconds
      items : 4,
      itemsDesktop : [1199,3],
      itemsDesktopSmall : [979,3]
   });
 
 });
 </script>